spring:
  application:
    name: blaybus777

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

#cloud:
#  aws:
#    credentials:
#      access-key: ${AWS_ACCESS_KEY}
#      secret-key: ${AWS_SECRET_KEY}
#    s3:
#      bucket: ${AWS_S3_BUCKET}
#    region:
#      static: ap-northeast-2
#      auto: false
#    stack:
#      auto: false
